### ISSUE TITLE
Pears tagged as logs.

### ISSUE THREAD

**Issue by NotAPotter** [ArshiaDPG/Pearfection-Fabric#2]
And they show up in any recipe burnable logs do.

**Comment by ArshiaDPG** [comment]
I'm not sure what the issue is here, are the lampears themselves appearing to be in the log tags?

**Comment by NotAPotter** [comment]
Yes, such as I can burn it into charcoal.

**Comment by ArshiaDPG** [comment]
Oh, well, that's embarrassing.
I'll fix it.
