### ISSUE TITLE
Callery chest boat recipe is incorrect, using planks instead of a boat

### ISSUE THREAD

**Issue by mintynoura** [ArshiaDPG/Pearfection-Fabric#6]
See https://github.com/ArshiaDPG/Pearfection-Fabric/blob/main/src/main/generated/data/pearfection/recipes/callery_chest_boat.json

![image](https://github.com/ArshiaDPG/Pearfection-Fabric/assets/107040228/07faa852-f545-448c-8a06-99d923efce67)

**Comment by ArshiaDPG** [comment]
Wow, I'm honestly not even sure how this happened.
Thanks for catching it.

**Comment by mintynoura** [comment]
It's no worries. Thanks for making a really cool mod :)

**Comment by ArshiaDPG** [comment]
I'm glad you like it. The fix should be out now :)
